const {chromium} = require('C:/Users/Owner/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.EDITOR_TEST_BROWSER || 'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const page=await browser.newPage();
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file:///'+path.join(__dirname,'index.html').replaceAll('\\','/'));
 let passed=0;
 async function check(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){console.log('FAIL '+name+' '+e.stack);process.exitCode=1;}}
 async function load(xml){await page.evaluate(xml=>{document.getElementById('importTextarea').value=xml;ImportXml();},xml);}
 async function select(start,end){await page.evaluate(([start,end])=>{EditorEl.focus();PendingStyle=null;SetSelectionOffsets({start,end});},[start,end]);}
 const xml=()=>page.locator('#xmlOutput').textContent();
 const runs=()=>page.evaluate(()=>Runs);
 await check('initial empty output',async()=>{assert.equal(await xml(),'');});
 await check('typing and escaped characters',async()=>{await page.locator('#editor').click();await page.keyboard.type('A & <B>');assert.equal(await xml(),'A &amp; &lt;B&gt;');assert.equal(await page.locator('#charCount').textContent(),'7');});
 await check('trailing and consecutive newlines',async()=>{await page.keyboard.press('End');await page.keyboard.press('Enter');await page.keyboard.press('Enter');assert.equal(await xml(),'A &amp; &lt;B&gt;<br /><br />');await page.keyboard.type('end');assert.equal(await xml(),'A &amp; &lt;B&gt;<br /><br />end');});
 await check('partial small caps removal',async()=>{await load('<sc>abcdef</sc>');await select(2,4);await page.getByTitle('Small Caps',{exact:true}).click();assert.deepEqual(await runs(),[{text:'ab',style:{sc:true}},{text:'cd',style:{}},{text:'ef',style:{sc:true}}]);});
 await check('partial color replacement preserves neighbors',async()=>{await load('<font color="#ff0000">abcdef</font>');await select(2,4);await page.evaluate(()=>ApplyColorToSelection('#00ff00','text',0));assert.equal((await runs())[1].style.color,'#00ff00');assert.equal((await runs())[0].style.color,'#ff0000');});
 await check('color over mixed nested styles',async()=>{await load('<font color="#ff0000">ab<font color="#0000ff">cd</font>ef</font>');await select(0,6);await page.evaluate(()=>ApplyColorToSelection('#00ff00','text',0));assert.equal((await runs()).length,1);assert.equal((await runs())[0].style.color,'#00ff00');});
 await check('font select keeps selection',async()=>{await load('abcdef');await select(1,4);await page.locator('#fontSizeSelect').selectOption('32');assert.deepEqual(await runs(),[{text:'a',style:{}},{text:'bcd',style:{size:'32'}},{text:'ef',style:{}}]);await page.locator('#fontFaceSelect').selectOption('Arial');assert.equal((await runs())[1].style.face,'Arial');});
 await check('format at caret affects newly typed text',async()=>{await load('abc');await select(3,3);await page.getByTitle('Small Caps',{exact:true}).click();await page.keyboard.type('d');assert.equal(await xml(),'abc<sc>d</sc>');await page.getByTitle('Small Caps',{exact:true}).click();await page.keyboard.type('e');assert.equal(await xml(),'abc<sc>d</sc>e');});
 await check('undo redo formatting, import and clear',async()=>{await load('abc');await select(0,3);await page.getByTitle('Bold',{exact:true}).click();assert.equal(await xml(),'<b>abc</b>');await page.keyboard.press('Control+z');assert.equal(await xml(),'abc');await page.keyboard.press('Control+Shift+z');assert.equal(await xml(),'<b>abc</b>');await page.getByRole('button',{name:'Clear',exact:true}).click();assert.equal(await xml(),'');await page.keyboard.press('Control+z');assert.equal(await xml(),'<b>abc</b>');});
 await check('entities decode once; whitespace retained',async()=>{await load('  &amp;lt; &#65; &apos; &#x1F600; <br />');assert.equal((await runs()).map(r=>r.text).join(''),"  &lt; A ' 😀 \n");assert.equal(await page.locator('#charCount').textContent(),'14');});
 await check('single quotes and > in attributes',async()=>{await load("<font face='A &quot;B&quot; &gt; C' size='24'>x</font>");assert.equal((await runs())[0].style.face,'A "B" > C');assert.ok((await xml()).includes('&quot;B&quot; &gt; C'));});
 await check('stroke attributes survive round trip',async()=>{await load('<stroke color="rgb(255,125,0)" th="2" tr="0.25" joins="miter" sizing="fixed">x</stroke>');const before=await runs();await load(await xml());assert.deepEqual(await runs(),before);assert.equal(before[0].style.strokeThickness,'2');});
 await check('nested opacity is replaced, not multiplied',async()=>{await load('<font transparency="0.5">a<font transparency="0">b</font></font>');assert.equal((await runs())[1].style.transparency,'0');assert.equal(await page.locator('#robloxPreview span').nth(1).evaluate(el=>getComputedStyle(el).color),'rgb(255, 255, 255)');});
 await check('invalid imports preserve existing text',async()=>{await load('KEEP');for(const bad of ['<b>x</i>','x & y','<script>alert(1)</script>','<font size="NaN">x</font>','<font color="red; background:url(x)">x</font>','<font transparency="2">x</font>','<stroke nonsense="1">x</stroke>']){await load(bad);assert.equal(await xml(),'KEEP');assert.notEqual(await page.locator('#importError').textContent(),'');}});
 await check('preview cannot interpret imported text as HTML',async()=>{await load('&lt;img src=x onerror=alert(1)&gt;');assert.equal(await page.locator('#robloxPreview img').count(),0);assert.equal(await page.locator('#robloxPreview').textContent(),'<img src=x onerror=alert(1)>');});
 await check('alpha zero and opaque replacement',async()=>{await load('abc');await select(0,3);await page.locator('#textColorBtn').click();await page.locator('#cpA').fill('0');await page.getByRole('button',{name:'Apply',exact:true}).click();assert.equal((await runs())[0].style.transparency,'1');await page.locator('#textColorBtn').click();assert.equal(await page.locator('#cpA').inputValue(),'0');await page.locator('#cpA').fill('255');await page.getByRole('button',{name:'Apply',exact:true}).click();assert.equal((await runs())[0].style.transparency,'0');});
 await check('8 digit hex preserves alpha',async()=>{await select(0,3);await page.locator('#textColorBtn').click();await page.locator('#cpHex').fill('#33669980');await page.getByRole('button',{name:'Apply',exact:true}).click();assert.equal((await runs())[0].style.color,'#336699');assert.equal((await runs())[0].style.transparency,'0.498');});
 await check('modal escape and keyboard focus',async()=>{await page.getByRole('button',{name:'Import XML',exact:true}).click();assert.equal(await page.locator('#importTextarea').evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#importModalOverlay').isVisible(),false);});
 await check('plain text paste excludes HTML',async()=>{await load('');await page.locator('#editor').click();await page.evaluate(()=>{const data=new DataTransfer();data.setData('text/plain','<b>hello</b>\r\nworld');data.setData('text/html','<img src=x onerror=alert(1)>');EditorEl.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});assert.equal(await xml(),'&lt;b&gt;hello&lt;/b&gt;<br />world');assert.equal(await page.locator('#editor img').count(),0);});
 await check('backspace and delete preserve output',async()=>{await load('abc');await select(3,3);await page.keyboard.press('Backspace');assert.equal(await xml(),'ab');await select(0,0);await page.keyboard.press('Delete');assert.equal(await xml(),'b');await page.keyboard.press('Control+z');assert.equal(await xml(),'ab');});
 await check('Luau quote slash and control escaping',async()=>{await load('');await page.evaluate(()=>InsertText('"\\\t\r\n'));const lua=await page.locator('#luaOutput').textContent();assert.ok(lua.includes('\\\\'));assert.ok(lua.includes('\\009'));assert.ok(!lua.includes('\r'));});
 await check('select all delete produces a truly empty document',async()=>{await load('<b>abc</b><br />def');await page.locator('#editor').focus();await page.keyboard.press('Control+a');await page.keyboard.press('Backspace');assert.equal(await xml(),'');assert.equal(await page.locator('#charCount').textContent(),'0');await page.keyboard.type('new');assert.equal((await runs()).map(r=>r.text).join(''),'new');});
 await check('delete through a style boundary',async()=>{await load('<b>ab</b><i>cd</i>ef');await select(1,5);await page.keyboard.press('Delete');assert.equal((await runs()).map(r=>r.text).join(''),'af');assert.equal((await runs())[0].style.b,true);assert.deepEqual((await runs())[1].style,{});});
 await check('delete blank lines one at a time',async()=>{await load('a<br /><br />');await select(3,3);await page.keyboard.press('Backspace');assert.equal(await xml(),'a<br />');await page.keyboard.press('Backspace');assert.equal(await xml(),'a');});
 await check('keyboard formatting shortcut',async()=>{await load('abc');await select(0,3);await page.keyboard.press('Control+b');assert.equal(await xml(),'<b>abc</b>');await page.keyboard.press('Control+i');assert.equal(await xml(),'<b><i>abc</i></b>');await page.keyboard.press('Control+b');assert.equal(await xml(),'<i>abc</i>');});
 await check('import itself can be undone and redone',async()=>{await load('before');await load('after');await page.keyboard.press('Control+z');assert.equal(await xml(),'before');await page.keyboard.press('Control+y');assert.equal(await xml(),'after');});
 await check('new edit discards obsolete redo branch',async()=>{await load('a');await page.keyboard.type('b');await page.keyboard.press('Control+z');await page.keyboard.type('c');await page.keyboard.press('Control+y');assert.equal(await xml(),'ac');});
 await check('unusual font names cannot create preview elements',async()=>{await load('<font face="&quot;&gt;&lt;img src=x onerror=alert(1)&gt;">text</font>');assert.equal(await page.locator('#robloxPreview img').count(),0);const before=await runs();await load(await xml());assert.deepEqual(await runs(),before);});
 await check('copy failure is handled and editor selection is preserved',async()=>{await load('abc');await select(1,2);await page.evaluate(async()=>{window.savedClipboard=Object.getOwnPropertyDescriptor(navigator,'clipboard');window.savedExec=document.execCommand;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(new Error('denied'))}});document.execCommand=()=>false;await CopyOutput();document.execCommand=window.savedExec;if(window.savedClipboard)Object.defineProperty(navigator,'clipboard',window.savedClipboard);else delete navigator.clipboard;});assert.equal(await page.locator('#copyXmlBtn').textContent(),'Copy failed');assert.deepEqual(await page.evaluate(()=>GetSelectionOffsets()),{start:1,end:2});});
 await check('random edits preserve text and XML round trips',async()=>{const result=await page.evaluate(()=>{let seed=42;const random=n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n;};ClearEditor();let expected='';for(let i=0;i<180;i++){let a=random(expected.length+1),b=random(expected.length+1);if(a>b)[a,b]=[b,a];SetSelectionOffsets({start:a,end:b});PendingStyle=null;if(random(3)===0){let text=['x','YZ','\n','<&>',' '][random(5)];InsertText(text);expected=expected.slice(0,a)+text+expected.slice(b);}else{ApplyStyle([{b:true},{b:false},{sc:true},{sc:false},{color:'#ff0000'},{color:'#00ff00',transparency:'0'}][random(6)]);}const actual=Runs.map(r=>r.text).join('');if(actual!==expected)throw new Error('text mismatch at '+i);if(JSON.stringify(ReadRuns(EditorEl))!==JSON.stringify(Runs))throw new Error('DOM mismatch at '+i);if(JSON.stringify(ParseRichText(RunsToXml(Runs)))!==JSON.stringify(Runs))throw new Error('XML mismatch at '+i);}return true;});assert.equal(result,true);});
 await check('composition retains formatting chosen at caret',async()=>{await load('abc');await select(3,3);await page.getByTitle('Small Caps',{exact:true}).click();const cdp=await page.context().newCDPSession(page);await cdp.send('Input.imeSetComposition',{text:'漢',selectionStart:1,selectionEnd:1});await cdp.send('Input.insertText',{text:'漢'});assert.equal(await xml(),'abc<sc>漢</sc>');await page.keyboard.press('Control+z');assert.equal(await xml(),'abc');await cdp.detach();});
 await check('keyboard font dropdown retains range',async()=>{await load('abcdef');await select(1,4);await page.locator('#fontSizeSelect').focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');const result=await runs();assert.equal(result[0].text,'a');assert.equal(result[1].text,'bcd');assert.ok(result[1].style.size);assert.equal(result[2].text,'ef');});
 await check('RGB and alpha bounds are clamped',async()=>{await load('x');await select(0,1);await page.locator('#textColorBtn').click();await page.locator('#cpR').fill('999');await page.locator('#cpG').fill('-5');await page.locator('#cpB').fill('10');await page.locator('#cpA').fill('-99');await page.getByRole('button',{name:'Apply',exact:true}).click();assert.equal((await runs())[0].style.color,'#ff000a');assert.equal((await runs())[0].style.transparency,'1');});
 await check('invalid hex leaves editor unchanged',async()=>{await load('x');await select(0,1);await page.locator('#textColorBtn').click();await page.locator('#cpHex').fill('#oops');await page.getByRole('button',{name:'Apply',exact:true}).click();assert.equal(await xml(),'x');assert.equal(await page.locator('#colorPickerPopup').isVisible(),true);await page.keyboard.press('Escape');});
 await check('mobile toolbar and picker stay on screen',async()=>{await page.setViewportSize({width:375,height:667});await load('abc');await select(0,3);await page.locator('#textColorBtn').click();const box=await page.locator('#colorPickerPopup').boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=376&&box.y+box.height<=668,JSON.stringify(box));await page.screenshot({path:path.join(__dirname,'mobile.png'),fullPage:true});await page.keyboard.press('Escape');});
 await check('no browser runtime errors',async()=>assert.deepEqual(errors,[]));
 console.log(`${passed} checks passed`);await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1;});


